version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INIT DB_ROOT_USERNAME: root
      MONGO_INIT DB_ROOT_PASSWORD: password
      MONGO_INIT DB_DATABASE: product-service
    volumes:
      - ./data:/data/db



    #after that use cmd in terminal inside product-service --> docker compose up -d